services:
- type: web
  name: tp-management-backend
  env: node
  buildCommand: npm install && npx prisma generate && npm run build
  startCommand: npx prisma db push --force-reset && npm start
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      sync: false